let
    Fonte = fFrete_base,
    Consolidado = fFrete,
    LinhasValidas = Table.SelectRows(Fonte, each [NUMERO_NF] <> null and Text.Trim([NUMERO_NF]) <> ""),
    JoinAuditoria = Table.NestedJoin(LinhasValidas, {"NUMERO_NF"}, Consolidado, {"NUMERO_NF"}, "FreteConsolidado", JoinKind.LeftOuter),
    ExpandAuditoria = Table.ExpandTableColumn(JoinAuditoria, "FreteConsolidado", {"NUMERO_CTE_PRINCIPAL", "QTD_CONHECIMENTOS", "QTD_LINHAS_ORIGEM", "FLAG_MULTIPLOS_CTES", "FLAG_DIVERGENCIA_TRANSPORTADORA", "FLAG_DIVERGENCIA_DESTINO", "FLAG_DIVERGENCIA_REGIONAL", "FLAG_EXCECAO_QUALIDADE"}, {"NUMERO_CTE_PRINCIPAL", "QTD_CONHECIMENTOS", "QTD_LINHAS_ORIGEM", "FLAG_MULTIPLOS_CTES", "FLAG_DIVERGENCIA_TRANSPORTADORA", "FLAG_DIVERGENCIA_DESTINO", "FLAG_DIVERGENCIA_REGIONAL", "FLAG_EXCECAO_QUALIDADE"}),
    FilteredExceptions = Table.SelectRows(ExpandAuditoria, each [FLAG_MULTIPLOS_CTES] = true or [FLAG_DIVERGENCIA_TRANSPORTADORA] = true or [FLAG_DIVERGENCIA_DESTINO] = true or [FLAG_DIVERGENCIA_REGIONAL] = true or [FLAG_NF_INVALIDA] = true or [FLAG_CTE_INVALIDO] = true or [FLAG_DATA_COLETA_INVALIDA] = true or [FLAG_DATA_CHEGADA_INVALIDA] = true or [FLAG_DATA_VENCIMENTO_INVALIDA] = true),
    SelectedColumns = Table.SelectColumns(FilteredExceptions, {"NUMERO_NF", "NUMERO_CTE_PRINCIPAL", "NUMERO_CTE", "DATA_NF", "DATA_CTE", "TRANSPORTADORA", "DESTINO", "REGIONAL", "VALOR_FRETE_CTE", "VALOR_FRETE_COTADO", "VALOR_NF", "VOLUME", "PESO", "COLETADO", "CHEGADA", "DATA_VENCIMENTO", "SITUACAO", "FLAG_NF_INVALIDA", "FLAG_CTE_INVALIDO", "FLAG_DATA_COLETA_INVALIDA", "FLAG_DATA_CHEGADA_INVALIDA", "FLAG_DATA_VENCIMENTO_INVALIDA", "QTD_CONHECIMENTOS", "QTD_LINHAS_ORIGEM", "FLAG_MULTIPLOS_CTES", "FLAG_DIVERGENCIA_TRANSPORTADORA", "FLAG_DIVERGENCIA_DESTINO", "FLAG_DIVERGENCIA_REGIONAL", "FLAG_EXCECAO_QUALIDADE", "ID_LINHA_ORIGEM", "TEXTO_NOTA", "TEXTO_CTE"}, MissingField.Ignore)
in
    SelectedColumns

