-- Ajuste a lista do IN conforme a necessidade
SELECT
    TRIM(rf.RDB$RELATION_NAME) AS TABELA,
    TRIM(rf.RDB$FIELD_NAME) AS COLUNA,
    rf.RDB$FIELD_POSITION + 1 AS ORDEM_COLUNA,
    CASE f.RDB$FIELD_TYPE
        WHEN 7 THEN 'SMALLINT'
        WHEN 8 THEN 'INTEGER'
        WHEN 10 THEN 'FLOAT'
        WHEN 12 THEN 'DATE'
        WHEN 13 THEN 'TIME'
        WHEN 14 THEN 'CHAR'
        WHEN 16 THEN
            CASE
                WHEN f.RDB$FIELD_SUB_TYPE = 1 THEN 'NUMERIC'
                WHEN f.RDB$FIELD_SUB_TYPE = 2 THEN 'DECIMAL'
                ELSE 'BIGINT'
            END
        WHEN 27 THEN 'DOUBLE'
        WHEN 35 THEN 'TIMESTAMP'
        WHEN 37 THEN 'VARCHAR'
        WHEN 261 THEN 'BLOB'
        ELSE 'TIPO_' || f.RDB$FIELD_TYPE
    END AS TIPO_DADO,
    COALESCE(f.RDB$CHARACTER_LENGTH, f.RDB$FIELD_LENGTH) AS TAMANHO,
    f.RDB$FIELD_PRECISION AS PRECISAO,
    ABS(f.RDB$FIELD_SCALE) AS ESCALA,
    CASE rf.RDB$NULL_FLAG
        WHEN 1 THEN 'NOT NULL'
        ELSE 'NULL'
    END AS NULABILIDADE
FROM RDB$RELATION_FIELDS rf
JOIN RDB$FIELDS f
  ON f.RDB$FIELD_NAME = rf.RDB$FIELD_SOURCE
WHERE TRIM(rf.RDB$RELATION_NAME) IN (
    'CLIENTE',
    'PRODUTO',
    'PRODUTOEMPRESA',
    'PEDIDO',
    'VENDAS',
    'CAIXAVENDA',
    'CAIXAVENDAITENS',
    'NFSAIDA',
    'NFSAIITE',
    'PRODUTOMOVIMENTACAO',
    'TITRECEB',
    'TITPAGAR'
)
ORDER BY
    TRIM(rf.RDB$RELATION_NAME),
    rf.RDB$FIELD_POSITION;
