SELECT FIRST 10 * FROM PEDIDO;
SELECT FIRST 10 * FROM VENDAS;
SELECT FIRST 10 * FROM CAIXAVENDA;
SELECT FIRST 10 * FROM CAIXAVENDAITENS;
SELECT FIRST 10 * FROM NFSAIDA;
SELECT FIRST 10 * FROM NFSAIITE;
