-- Primeira versao da dClientes
-- Base escolhida: CLIENTE
-- Motivo: e a dimensao principal para vendas, pedidos e financeiro
--
-- Tabela usada:
--   CLIENTE = cadastro mestre de clientes
--
-- Observacoes:
-- - CODIGO_CLIENTE usa o codigo de negocio, que foi a chave mais consistente nas fatos
-- - NOME_CLIENTE prioriza NOME e usa RAZAOSOCIAL como fallback
-- - STATUS_CLIENTE tenta resumir ATIVO e SITCADASTRO
-- - VENDEDOR e forma de pagamento ficam mantidos como codigos tecnicos

SELECT
    c.ID AS ID_CLIENTE,
    c.CODIGO AS CODIGO_CLIENTE,
    COALESCE(
        NULLIF(TRIM(c.NOME), ''),
        NULLIF(TRIM(c.RAZAOSOCIAL), '')
    ) AS NOME_CLIENTE,
    c.RAZAOSOCIAL AS RAZAO_SOCIAL,
    c.NOMEABREVIADO AS NOME_ABREVIADO,
    c.FISICAJURIDICA AS TIPO_PESSOA,
    c.CGCCPF AS DOCUMENTO,
    c.RGINSCREST AS INSCRICAO_RG,
    c.CONTATO AS CONTATO,
    c.FONE AS TELEFONE,
    c.CELULAR AS CELULAR,
    c.SITE AS SITE,
    c.ENDERECO AS ENDERECO,
    c.NUMIMOVEL AS NUMERO_ENDERECO,
    c.COMPLEMENTO AS COMPLEMENTO_ENDERECO,
    c.BAIRRO AS BAIRRO,
    c.CEP AS CEP,
    c.CIDADE AS CIDADE,
    c.ESTADO AS UF,
    c.PAIS_IBGE AS CODIGO_PAIS_IBGE,
    c.CIDIBGE AS CODIGO_CIDADE_IBGE,
    c.UFIBGE AS CODIGO_UF_IBGE,
    c.GRUPO AS GRUPO_CLIENTE,
    c.RAMOATIVIDADE AS RAMO_ATIVIDADE,
    c.FILIAL AS FILIAL_CADASTRO,
    c.IDVENDEDOR AS VENDEDOR_PADRAO_CODIGO,
    c.IDPROMOTOR AS PROMOTOR_CODIGO,
    c.IDFORMAPAGAMENTO AS FORMA_PAGAMENTO_PADRAO_CODIGO,
    c.IDTIPMVSAI AS TIPO_MOVIMENTO_PADRAO_CODIGO,
    c.LIMITECREDITO AS LIMITE_CREDITO,
    c.VALORMAXFATURA AS VALOR_MAXIMO_FATURA,
    c.CONSUMIDORFINAL AS CONSUMIDOR_FINAL,
    c.SITCADASTRO AS SITUACAO_CADASTRAL,
    c.ATIVO AS ATIVO_FLAG,
    CASE
        WHEN COALESCE(c.ATIVO, 'S') = 'N' THEN 'INATIVO'
        WHEN COALESCE(c.SITCADASTRO, '') IN ('0', 'B', 'I') THEN 'RESTRITO'
        ELSE 'ATIVO'
    END AS STATUS_CLIENTE,
    c.DATACADASTRO AS DATA_CADASTRO,
    c.DATAEMISSAO AS DATA_EMISSAO_DOCUMENTO,
    c.DATAULTIMAATUAL AS DATA_ULTIMA_ATUALIZACAO,
    c.DATAULTIMAVENDA AS DATA_ULTIMA_VENDA,
    c.DATASITCADASTRO AS DATA_SITUACAO_CADASTRAL,
    c.ULTIMAALTERACAODB AS DATA_ULTIMA_ALTERACAO_BANCO
FROM CLIENTE c;
