-- Query final da dimensao de clientes para a primeira analise

SELECT
    c.CODIGO AS CODIGO_CLIENTE,
    COALESCE(
        NULLIF(TRIM(c.NOME), ''),
        NULLIF(TRIM(c.RAZAOSOCIAL), '')
    ) AS NOME_CLIENTE,
    c.RAZAOSOCIAL AS RAZAO_SOCIAL,
    c.NOMEABREVIADO AS NOME_ABREVIADO,
    c.FISICAJURIDICA AS TIPO_PESSOA,
    c.CEP AS CEP,
    c.CIDADE AS CIDADE,
    c.ESTADO AS UF,
    c.GRUPO AS GRUPO_CLIENTE,
    cg.NOME AS GRUPO,
    c.CONSUMIDORFINAL AS CONSUMIDOR_FINAL,
    c.ATIVO AS ATIVO_FLAG
FROM CLIENTE c
LEFT JOIN CLIGRUPO cg
  ON cg.CODIGO = c.GRUPO;
