-- Primeira versao da dProdutos
-- Base escolhida: PRODUTO + PRODUTOEMPRESA
-- Motivo: PRODUTO concentra o cadastro mestre e PRODUTOEMPRESA traz atributos por filial
--
-- Tabelas usadas:
--   PRODUTO         = cadastro mestre de produtos
--   PRODUTOEMPRESA  = complemento do produto por empresa / filial
--
-- Observacoes:
-- - CODIGO_PRODUTO usa o codigo de negocio, enquanto ID_PRODUTO e a chave tecnica
-- - DESCRICAO_PRODUTO prioriza NOME
-- - STATUS_PRODUTO tenta resumir o status do cadastro base
-- - PRECO_VENDA_FILIAL e PRECO_MINIMO_FILIAL usam PRODUTOEMPRESA quando disponivel

SELECT
    pe.EMPRESA AS EMPRESA_FILIAL,
    p.ID AS ID_PRODUTO,
    p.CODIGO AS CODIGO_PRODUTO,
    COALESCE(NULLIF(TRIM(p.NOME), ''), p.CODIGO) AS DESCRICAO_PRODUTO,
    p.REFERENCIA AS REFERENCIA,
    p.CODFABRICANTE AS CODIGO_FABRICANTE,
    p.NOMEFABRICANTE AS NOME_FABRICANTE,
    p.MARCA AS MARCA,
    p.GRUPO AS GRUPO_PRODUTO,
    p.GRUPOGERAL AS GRUPO_GERAL,
    p.GRUPO_CENTRO_CUSTO AS GRUPO_CENTRO_CUSTO,
    p.DEPARTAMENTO AS DEPARTAMENTO,
    p.CATEGORIA AS CATEGORIA,
    p.CURVAABCD AS CURVA_ABC,
    p.CURVAXYZ AS CURVA_XYZ,
    p.STATUS AS STATUS_CADASTRO,
    CASE
        WHEN COALESCE(p.STATUS, '') IN ('I', 'N') THEN 'INATIVO'
        ELSE 'ATIVO'
    END AS STATUS_PRODUTO,
    p.TIPOVENDA AS TIPO_VENDA,
    p.TIPO_ITEM AS TIPO_ITEM,
    p.ORIGEM AS ORIGEM_PRODUTO,
    p.IDUNIDADE AS ID_UNIDADE,
    p.IDUNIDADEPADRAO AS ID_UNIDADE_PADRAO,
    p.IDCONVERSAOUNID AS ID_CONVERSAO_UNIDADE,
    p.USAGRADE AS USA_GRADE,
    p.IDPRODUTOGRADE AS ID_PRODUTO_GRADE,
    p.IDPRODUTOMODELO AS ID_PRODUTO_MODELO,
    p.IDAPLICACAO AS ID_APLICACAO,
    p.PRECOVENDA AS PRECO_VENDA_CADASTRO,
    pe.PROEMPREPRECOVENDA AS PRECO_VENDA_FILIAL,
    p.PRECOMINIMO AS PRECO_MINIMO_CADASTRO,
    pe.PROEMPREPRECOMINIMO AS PRECO_MINIMO_FILIAL,
    p.MARGEMLUCRO AS MARGEM_LUCRO_CADASTRO,
    pe.PROEMPREMARGEMLUCRO AS MARGEM_LUCRO_FILIAL,
    p.PESO AS PESO,
    p.PESOLIQ AS PESO_LIQUIDO,
    p.EMBALAGEMMINIMA AS EMBALAGEM_MINIMA,
    p.QUANTIDADE AS QUANTIDADE_CADASTRO,
    p.QUANTIDADEMINIMA AS QUANTIDADE_MINIMA,
    p.VALIDADE AS VALIDADE_DIAS,
    p.DATAALTERPRECO AS DATA_ALTERACAO_PRECO,
    p.DATAULTVENDA AS DATA_ULTIMA_VENDA,
    p.DATAULTCOMPRA AS DATA_ULTIMA_COMPRA,
    p.DATAULTDESC AS DATA_ULTIMO_DESCONTO,
    p.DATACADASTRO AS DATA_CADASTRO,
    p.ULTIMAALTERACAODB AS DATA_ULTIMA_ALTERACAO_BANCO,
    pe.SITUACAO_TRIBUTARIA AS SITUACAO_TRIBUTARIA_FILIAL,
    pe.ALIQUOTAICMS AS ALIQUOTA_ICMS_FILIAL,
    pe.LOCALIZACAO AS LOCALIZACAO_ESTOQUE,
    pe.PROMOCAO AS PROMOCAO_FLAG,
    pe.QTDMINIMA AS QUANTIDADE_MINIMA_FILIAL,
    pe.TAXACOMISSAO AS TAXA_COMISSAO_FILIAL,
    pe.TRIBUTAIPI AS TRIBUTA_IPI,
    pe.IDCLASSTRIBSIBSCBS AS ID_CLASSIFICACAO_TRIBUTARIA,
    pe.ULTIMAALTERACAODB AS DATA_ULTIMA_ALTERACAO_FILIAL
FROM PRODUTO p
LEFT JOIN PRODUTOEMPRESA pe
  ON pe.IDPRODUTO = p.ID;
