-- Query final da dimensao de produtos para a primeira analise

SELECT
    p.CODIGO AS CODIGO_PRODUTO,
    COALESCE(NULLIF(TRIM(p.NOME), ''), p.CODIGO) AS DESCRICAO_PRODUTO,
    pm.NOME AS MARCA,
    pg.NOME AS GRUPO_PRODUTO,
    pgr.NOME AS GRUPO_GERAL,
    p.STATUS AS STATUS_CADASTRO,
    CASE
        WHEN COALESCE(p.STATUS, '') IN ('I', 'N') THEN 'INATIVO'
        ELSE 'ATIVO'
    END AS STATUS_PRODUTO,
    p.PRECOVENDA AS PRECO_VENDA_CADASTRO
FROM PRODUTO p
LEFT JOIN PROMARCA pm
  ON pm.CODIGO = p.MARCA
LEFT JOIN PROGRUPO pg
  ON pg.CODIGO = p.GRUPO
LEFT JOIN PROGERAL pgr
  ON pgr.CODIGO = p.GRUPOGERAL;
