-- Primeira versao da fPedidos
-- Base escolhida: PEDIDO + PEDITE + CLIENTE + PRODUTO
-- Motivo: e a trilha mais confiavel do inventario para carteira comercial e pedidos
--
-- Tabelas usadas:
--   PEDIDO   = cabecalho comercial do pedido
--   PEDITE   = itens do pedido
--   CLIENTE  = dimensao de cliente
--   PRODUTO  = dimensao de produto
--
-- Observacoes:
-- - CODIGO_PEDIDO usa NUMPEDIDO, com fallback para ID
-- - DATA_PEDIDO usa DATAEMISSAO e, se nula, DATAENTRADA
-- - CUSTO_UNITARIO usa a melhor cadeia disponivel no item:
--     CUSTOULTIMACOMPRA -> CUSTOREPOSICAO -> CUSTOMEDIO -> CUSTOOPERACIONAL
-- - STATUS_PEDIDO_ITEM resume status do cabecalho e do item
-- - VENDEDOR foi mantido como codigo tecnico do cabecalho: IDVENDEDOR

SELECT
    p.EMPRESA AS EMPRESA_FILIAL,
    COALESCE(p.DATAEMISSAO, p.DATAENTRADA) AS DATA_PEDIDO,
    COALESCE(
        CAST(p.NUMPEDIDO AS VARCHAR(20)),
        CAST(p.ID AS VARCHAR(20))
    ) AS CODIGO_PEDIDO,
    c.CODIGO AS CODIGO_CLIENTE,
    COALESCE(
        NULLIF(TRIM(c.NOME), ''),
        NULLIF(TRIM(c.RAZAOSOCIAL), '')
    ) AS NOME_CLIENTE,
    pr.CODIGO AS CODIGO_PRODUTO,
    COALESCE(
        NULLIF(TRIM(pr.NOME), ''),
        NULLIF(TRIM(i.PRODUTONOME), '')
    ) AS DESCRICAO_PRODUTO,
    i.QUANTIDADE AS QUANTIDADE,
    COALESCE(i.VALORUNITLIQUIDO, i.VALORUNITARIO) AS VALOR_UNITARIO,
    COALESCE(i.VALORITEMLIQUIDO, i.VALORITEMBRUTO) AS VALOR_TOTAL,
    COALESCE(i.CUSTOULTIMACOMPRA, i.CUSTOREPOSICAO, i.CUSTOMEDIO, i.CUSTOOPERACIONAL) AS CUSTO_UNITARIO,
    COALESCE(i.CUSTOULTIMACOMPRA, i.CUSTOREPOSICAO, i.CUSTOMEDIO, i.CUSTOOPERACIONAL) * COALESCE(i.QUANTIDADE, 0) AS CUSTO_TOTAL,
    p.IDVENDEDOR AS VENDEDOR_CODIGO,
    CASE
        WHEN COALESCE(p.STATUS, '') = 'C' THEN 'CANCELADO'
        WHEN COALESCE(p.SITUACAO, '') = 'C' THEN 'CANCELADO'
        WHEN COALESCE(i.STATUS, '') = 'C' THEN 'ITEM_CANCELADO'
        WHEN COALESCE(i.PENDENCIA, '') = 'S' THEN 'PENDENTE'
        WHEN COALESCE(p.QUITADO, '') = 'S' THEN 'QUITADO'
        WHEN COALESCE(p.CONFERIDO, '') = 'S' THEN 'CONFERIDO'
        ELSE 'ATIVO'
    END AS STATUS_PEDIDO_ITEM,
    p.ID AS ID_PEDIDO,
    i.ID AS ID_PEDITE,
    i.ITEM AS ITEM_PEDIDO,
    p.CLIENTE AS CODIGO_CLIENTE_ORIGEM,
    i.IDPRODUTO AS ID_PRODUTO,
    p.IDFORMAPAGAMENTO AS ID_FORMAPAGAMENTO,
    p.IDTIPMVSAI AS ID_TIPO_MOVIMENTO,
    p.DATAPREVISTA AS DATA_PREVISTA,
    p.ORIGEM AS ORIGEM_PEDIDO,
    p.PEDIDOINTEGRACAO AS PEDIDO_INTEGRACAO
FROM PEDIDO p
JOIN PEDITE i
  ON i.IDPEDIDO = p.ID
LEFT JOIN CLIENTE c
  ON c.CODIGO = p.CLIENTE
LEFT JOIN PRODUTO pr
  ON pr.ID = i.IDPRODUTO
WHERE COALESCE(p.STATUS, '') <> 'C'
  AND COALESCE(p.SITUACAO, '') <> 'C';
