-- Query final da primeira analise comercial
-- Base escolhida: NFSAIDA + NFSAIITE + CLIENTE + PRODUTO + TRANSPOR
-- Observacao: dCalendario sera mantida no Power BI

SELECT
    COALESCE(n.DATASAIDA, n.DATAEMISSAO) AS DATA_VENDA,
    COALESCE(
        NULLIF(TRIM(n.NOTAFISCAL), ''),
        NULLIF(TRIM(n.NUMERO), ''),
        CAST(n.ID AS VARCHAR(20))
    ) AS NOTA_FISCAL,
    c.CODIGO AS CODIGO_CLIENTE,
    p.CODIGO AS CODIGO_PRODUTO,
    i.QUANTIDADE AS QUANTIDADE_ITEM,
    i.VALORUNITARIO AS VALOR_UNITARIO,
    COALESCE(i.VALORITEMLIQUIDO, i.VALORITEMBRUTO) AS VALOR_TOTAL_ITEM,
    COALESCE(i.CUSTOMEDIO, i.CUSTOOPERACIONAL) AS CUSTO_UNITARIO,
    COALESCE(i.CUSTOMEDIO, i.CUSTOOPERACIONAL) * COALESCE(i.QUANTIDADE, 0) AS CUSTO_TOTAL,
    n.VALORPRODUTOS,
    n.PESOBRUTO,
    n.QUANTIDADE AS QUANTIDADE_NOTA,
    t.NOME AS TRANSPORTADOR,
    n.IDVENDEDOR AS VENDEDOR_CODIGO,
    CASE
        WHEN COALESCE(n.CANCELADA, 'N') = 'S' THEN 'CANCELADA'
        WHEN COALESCE(n.NOTAANULADA, 'N') = 'S' THEN 'ANULADA'
        WHEN NULLIF(TRIM(n.STATUSNFE), '') IS NOT NULL THEN 'STATUSNFE_' || TRIM(n.STATUSNFE)
        WHEN COALESCE(n.CONFERIDO, 'N') = 'S' THEN 'CONFERIDA'
        ELSE 'ATIVA'
    END AS STATUS_CANCELAMENTO,
    i.ITEM AS ITEM_VENDA,
    n.NUMEROORIGEM AS PEDIDO,
    n.IDFORMAPAGAMENTO AS ID_FORMAPAGAMENTO,
    n.IDTIPMVSAI AS ID_TIPO_MOVIMENTO
FROM NFSAIDA n
JOIN NFSAIITE i
    ON i.IDNFSAIDA = n.ID
LEFT JOIN CLIENTE c
    ON c.CODIGO = n.CLIENTE
LEFT JOIN PEDIDO ped
    ON ped.ID = n.NUMEROORIGEM
LEFT JOIN PRODUTO p
    ON p.ID = i.IDPRODUTO
LEFT JOIN TRANSPOR t
    ON t.CODIGO = n.TRANSPORTADOR
WHERE COALESCE(n.CANCELADA, 'N') <> 'S'
  AND COALESCE(n.DATASAIDA, n.DATAEMISSAO) >= '2024-01-01';
