-- Validacao de qualidade da fPedidos
-- Base validada:
--   PEDIDO  -> cabecalho do pedido
--   PEDITE  -> itens do pedido
--   CLIENTE -> dimensao de cliente
--   PRODUTO -> dimensao de produto
--
-- Objetivo:
-- - medir cobertura das principais juncaoes
-- - identificar campos importantes nao preenchidos
-- - gerar exemplos de registros problematicos antes da carga no Power BI

-- ============================================================
-- 1. RESUMO GERAL DE COBERTURA
-- ============================================================
SELECT
    COUNT(*) AS TOTAL_LINHAS_FPEDIDOS,
    COUNT(DISTINCT p.ID) AS TOTAL_PEDIDOS,
    SUM(CASE WHEN c.CODIGO IS NOT NULL THEN 1 ELSE 0 END) AS LINHAS_COM_CLIENTE,
    SUM(CASE WHEN c.CODIGO IS NULL THEN 1 ELSE 0 END) AS LINHAS_SEM_CLIENTE,
    SUM(CASE WHEN pr.ID IS NOT NULL THEN 1 ELSE 0 END) AS LINHAS_COM_PRODUTO,
    SUM(CASE WHEN pr.ID IS NULL THEN 1 ELSE 0 END) AS LINHAS_SEM_PRODUTO,
    SUM(CASE WHEN p.IDVENDEDOR IS NOT NULL THEN 1 ELSE 0 END) AS LINHAS_COM_VENDEDOR,
    SUM(CASE WHEN p.IDVENDEDOR IS NULL THEN 1 ELSE 0 END) AS LINHAS_SEM_VENDEDOR,
    SUM(CASE WHEN COALESCE(p.DATAEMISSAO, p.DATAENTRADA) IS NOT NULL THEN 1 ELSE 0 END) AS LINHAS_COM_DATA_PEDIDO,
    SUM(CASE WHEN COALESCE(p.DATAEMISSAO, p.DATAENTRADA) IS NULL THEN 1 ELSE 0 END) AS LINHAS_SEM_DATA_PEDIDO,
    SUM(CASE WHEN COALESCE(p.NUMPEDIDO, p.ID) IS NOT NULL THEN 1 ELSE 0 END) AS LINHAS_COM_CODIGO_PEDIDO,
    SUM(CASE WHEN COALESCE(p.NUMPEDIDO, p.ID) IS NULL THEN 1 ELSE 0 END) AS LINHAS_SEM_CODIGO_PEDIDO,
    SUM(CASE WHEN COALESCE(i.VALORUNITLIQUIDO, i.VALORUNITARIO) IS NOT NULL THEN 1 ELSE 0 END) AS LINHAS_COM_VALOR_UNITARIO,
    SUM(CASE WHEN COALESCE(i.VALORUNITLIQUIDO, i.VALORUNITARIO) IS NULL THEN 1 ELSE 0 END) AS LINHAS_SEM_VALOR_UNITARIO,
    SUM(CASE WHEN COALESCE(i.VALORITEMLIQUIDO, i.VALORITEMBRUTO) IS NOT NULL THEN 1 ELSE 0 END) AS LINHAS_COM_VALOR_TOTAL,
    SUM(CASE WHEN COALESCE(i.VALORITEMLIQUIDO, i.VALORITEMBRUTO) IS NULL THEN 1 ELSE 0 END) AS LINHAS_SEM_VALOR_TOTAL,
    SUM(CASE WHEN COALESCE(i.CUSTOULTIMACOMPRA, i.CUSTOREPOSICAO, i.CUSTOMEDIO, i.CUSTOOPERACIONAL) IS NOT NULL THEN 1 ELSE 0 END) AS LINHAS_COM_CUSTO,
    SUM(CASE WHEN COALESCE(i.CUSTOULTIMACOMPRA, i.CUSTOREPOSICAO, i.CUSTOMEDIO, i.CUSTOOPERACIONAL) IS NULL THEN 1 ELSE 0 END) AS LINHAS_SEM_CUSTO,
    CAST(
        100.0 * SUM(CASE WHEN c.CODIGO IS NOT NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0)
        AS NUMERIC(15, 2)
    ) AS PCT_COBERTURA_CLIENTE,
    CAST(
        100.0 * SUM(CASE WHEN pr.ID IS NOT NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0)
        AS NUMERIC(15, 2)
    ) AS PCT_COBERTURA_PRODUTO,
    CAST(
        100.0 * SUM(CASE WHEN p.IDVENDEDOR IS NOT NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0)
        AS NUMERIC(15, 2)
    ) AS PCT_COBERTURA_VENDEDOR,
    CAST(
        100.0 * SUM(CASE WHEN COALESCE(i.CUSTOULTIMACOMPRA, i.CUSTOREPOSICAO, i.CUSTOMEDIO, i.CUSTOOPERACIONAL) IS NOT NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0)
        AS NUMERIC(15, 2)
    ) AS PCT_COBERTURA_CUSTO
FROM PEDIDO p
JOIN PEDITE i
  ON i.IDPEDIDO = p.ID
LEFT JOIN CLIENTE c
  ON c.CODIGO = p.CLIENTE
LEFT JOIN PRODUTO pr
  ON pr.ID = i.IDPRODUTO
WHERE COALESCE(p.STATUS, '') <> 'C'
  AND COALESCE(p.SITUACAO, '') <> 'C';

-- ============================================================
-- 2. RESUMO POR EMPRESA
-- ============================================================
SELECT
    p.EMPRESA,
    COUNT(*) AS TOTAL_LINHAS,
    COUNT(DISTINCT p.ID) AS TOTAL_PEDIDOS,
    SUM(CASE WHEN c.CODIGO IS NULL THEN 1 ELSE 0 END) AS LINHAS_SEM_CLIENTE,
    SUM(CASE WHEN pr.ID IS NULL THEN 1 ELSE 0 END) AS LINHAS_SEM_PRODUTO,
    SUM(CASE WHEN p.IDVENDEDOR IS NULL THEN 1 ELSE 0 END) AS LINHAS_SEM_VENDEDOR,
    SUM(CASE WHEN COALESCE(i.CUSTOULTIMACOMPRA, i.CUSTOREPOSICAO, i.CUSTOMEDIO, i.CUSTOOPERACIONAL) IS NULL THEN 1 ELSE 0 END) AS LINHAS_SEM_CUSTO,
    CAST(
        100.0 * SUM(CASE WHEN c.CODIGO IS NOT NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0)
        AS NUMERIC(15, 2)
    ) AS PCT_COBERTURA_CLIENTE,
    CAST(
        100.0 * SUM(CASE WHEN pr.ID IS NOT NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0)
        AS NUMERIC(15, 2)
    ) AS PCT_COBERTURA_PRODUTO
FROM PEDIDO p
JOIN PEDITE i
  ON i.IDPEDIDO = p.ID
LEFT JOIN CLIENTE c
  ON c.CODIGO = p.CLIENTE
LEFT JOIN PRODUTO pr
  ON pr.ID = i.IDPRODUTO
WHERE COALESCE(p.STATUS, '') <> 'C'
  AND COALESCE(p.SITUACAO, '') <> 'C'
GROUP BY p.EMPRESA
ORDER BY p.EMPRESA;

-- ============================================================
-- 3. DISTRIBUICAO DE STATUS
-- ============================================================
SELECT
    CASE
        WHEN COALESCE(p.STATUS, '') = 'C' THEN 'CANCELADO'
        WHEN COALESCE(p.SITUACAO, '') = 'C' THEN 'CANCELADO'
        WHEN COALESCE(i.STATUS, '') = 'C' THEN 'ITEM_CANCELADO'
        WHEN COALESCE(i.PENDENCIA, '') = 'S' THEN 'PENDENTE'
        WHEN COALESCE(p.QUITADO, '') = 'S' THEN 'QUITADO'
        WHEN COALESCE(p.CONFERIDO, '') = 'S' THEN 'CONFERIDO'
        ELSE 'ATIVO'
    END AS STATUS_PEDIDO_ITEM,
    COUNT(*) AS TOTAL_LINHAS,
    COUNT(DISTINCT p.ID) AS TOTAL_PEDIDOS
FROM PEDIDO p
JOIN PEDITE i
  ON i.IDPEDIDO = p.ID
WHERE COALESCE(p.STATUS, '') <> 'C'
  AND COALESCE(p.SITUACAO, '') <> 'C'
GROUP BY 1
ORDER BY TOTAL_LINHAS DESC;

-- ============================================================
-- 4. EXEMPLOS DE ITENS SEM CLIENTE
-- ============================================================
SELECT FIRST 30
    p.EMPRESA,
    p.ID AS ID_PEDIDO,
    p.NUMPEDIDO,
    COALESCE(p.DATAEMISSAO, p.DATAENTRADA) AS DATA_PEDIDO,
    p.CLIENTE AS CODIGO_CLIENTE_ORIGEM,
    i.ID AS ID_PEDITE,
    i.ITEM,
    i.IDPRODUTO,
    i.PRODUTONOME,
    COALESCE(i.VALORITEMLIQUIDO, i.VALORITEMBRUTO) AS VALOR_TOTAL
FROM PEDIDO p
JOIN PEDITE i
  ON i.IDPEDIDO = p.ID
LEFT JOIN CLIENTE c
  ON c.CODIGO = p.CLIENTE
WHERE COALESCE(p.STATUS, '') <> 'C'
  AND COALESCE(p.SITUACAO, '') <> 'C'
  AND c.CODIGO IS NULL
ORDER BY COALESCE(p.DATAEMISSAO, p.DATAENTRADA) DESC, p.ID, i.ITEM;

-- ============================================================
-- 5. EXEMPLOS DE ITENS SEM PRODUTO
-- ============================================================
SELECT FIRST 30
    p.EMPRESA,
    p.ID AS ID_PEDIDO,
    p.NUMPEDIDO,
    COALESCE(p.DATAEMISSAO, p.DATAENTRADA) AS DATA_PEDIDO,
    p.CLIENTE AS CODIGO_CLIENTE_ORIGEM,
    i.ID AS ID_PEDITE,
    i.ITEM,
    i.IDPRODUTO,
    i.PRODUTONOME,
    COALESCE(i.VALORITEMLIQUIDO, i.VALORITEMBRUTO) AS VALOR_TOTAL
FROM PEDIDO p
JOIN PEDITE i
  ON i.IDPEDIDO = p.ID
LEFT JOIN PRODUTO pr
  ON pr.ID = i.IDPRODUTO
WHERE COALESCE(p.STATUS, '') <> 'C'
  AND COALESCE(p.SITUACAO, '') <> 'C'
  AND pr.ID IS NULL
ORDER BY COALESCE(p.DATAEMISSAO, p.DATAENTRADA) DESC, p.ID, i.ITEM;

-- ============================================================
-- 6. EXEMPLOS DE ITENS SEM CUSTO
-- ============================================================
SELECT FIRST 30
    p.EMPRESA,
    p.ID AS ID_PEDIDO,
    p.NUMPEDIDO,
    COALESCE(p.DATAEMISSAO, p.DATAENTRADA) AS DATA_PEDIDO,
    i.ID AS ID_PEDITE,
    i.ITEM,
    i.IDPRODUTO,
    i.PRODUTONOME,
    i.QUANTIDADE,
    COALESCE(i.VALORUNITLIQUIDO, i.VALORUNITARIO) AS VALOR_UNITARIO,
    COALESCE(i.VALORITEMLIQUIDO, i.VALORITEMBRUTO) AS VALOR_TOTAL
FROM PEDIDO p
JOIN PEDITE i
  ON i.IDPEDIDO = p.ID
WHERE COALESCE(p.STATUS, '') <> 'C'
  AND COALESCE(p.SITUACAO, '') <> 'C'
  AND COALESCE(i.CUSTOULTIMACOMPRA, i.CUSTOREPOSICAO, i.CUSTOMEDIO, i.CUSTOOPERACIONAL) IS NULL
ORDER BY COALESCE(p.DATAEMISSAO, p.DATAENTRADA) DESC, p.ID, i.ITEM;

-- ============================================================
-- 7. EXEMPLOS DE ITENS SEM VENDEDOR
-- ============================================================
SELECT FIRST 30
    p.EMPRESA,
    p.ID AS ID_PEDIDO,
    p.NUMPEDIDO,
    COALESCE(p.DATAEMISSAO, p.DATAENTRADA) AS DATA_PEDIDO,
    p.CLIENTE AS CODIGO_CLIENTE_ORIGEM,
    i.ID AS ID_PEDITE,
    i.ITEM,
    i.IDPRODUTO,
    i.PRODUTONOME,
    COALESCE(i.VALORITEMLIQUIDO, i.VALORITEMBRUTO) AS VALOR_TOTAL
FROM PEDIDO p
JOIN PEDITE i
  ON i.IDPEDIDO = p.ID
WHERE COALESCE(p.STATUS, '') <> 'C'
  AND COALESCE(p.SITUACAO, '') <> 'C'
  AND p.IDVENDEDOR IS NULL
ORDER BY COALESCE(p.DATAEMISSAO, p.DATAENTRADA) DESC, p.ID, i.ITEM;

-- ============================================================
-- 8. EXEMPLOS DE PEDIDOS COM DATA NULA OU CODIGO NULO
-- ============================================================
SELECT FIRST 30
    p.EMPRESA,
    p.ID AS ID_PEDIDO,
    p.NUMPEDIDO,
    p.DATAEMISSAO,
    p.DATAENTRADA,
    p.CLIENTE AS CODIGO_CLIENTE_ORIGEM,
    p.IDVENDEDOR,
    p.STATUS,
    p.SITUACAO,
    p.ORIGEM
FROM PEDIDO p
WHERE COALESCE(p.STATUS, '') <> 'C'
  AND COALESCE(p.SITUACAO, '') <> 'C'
  AND (
      COALESCE(p.DATAEMISSAO, p.DATAENTRADA) IS NULL
      OR COALESCE(p.NUMPEDIDO, p.ID) IS NULL
  )
ORDER BY p.ID DESC;
