-- Validacao do relacionamento entre NFSAIDA e PEDIDO
-- Hipotese validada:
--   NFSAIDA.NUMEROORIGEM -> PEDIDO.ID
-- Resultado esperado:
--   medir quantas notas encontram pedido e quantas ficam sem correspondencia

-- 1. Resumo geral de cobertura
SELECT
    COUNT(*) AS TOTAL_NFSAIDA,
    SUM(CASE WHEN n.NUMEROORIGEM IS NOT NULL THEN 1 ELSE 0 END) AS NF_COM_NUMEROORIGEM,
    SUM(CASE WHEN p.ID IS NOT NULL THEN 1 ELSE 0 END) AS NF_COM_PEDIDO_ENCONTRADO,
    SUM(CASE WHEN n.NUMEROORIGEM IS NOT NULL AND p.ID IS NULL THEN 1 ELSE 0 END) AS NF_COM_ORIGEM_SEM_PEDIDO,
    CAST(
        100.0 * SUM(CASE WHEN p.ID IS NOT NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0)
        AS NUMERIC(15, 2)
    ) AS PERC_NF_COM_PEDIDO,
    CAST(
        100.0 * SUM(CASE WHEN n.NUMEROORIGEM IS NOT NULL AND p.ID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0)
        AS NUMERIC(15, 2)
    ) AS PERC_NF_SEM_MATCH
FROM NFSAIDA n
LEFT JOIN PEDIDO p
  ON p.ID = n.NUMEROORIGEM;

-- 2. Resumo por empresa
SELECT
    n.EMPRESA,
    COUNT(*) AS TOTAL_NFSAIDA,
    SUM(CASE WHEN n.NUMEROORIGEM IS NOT NULL THEN 1 ELSE 0 END) AS NF_COM_NUMEROORIGEM,
    SUM(CASE WHEN p.ID IS NOT NULL THEN 1 ELSE 0 END) AS NF_COM_PEDIDO_ENCONTRADO,
    SUM(CASE WHEN n.NUMEROORIGEM IS NOT NULL AND p.ID IS NULL THEN 1 ELSE 0 END) AS NF_COM_ORIGEM_SEM_PEDIDO,
    CAST(
        100.0 * SUM(CASE WHEN p.ID IS NOT NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0)
        AS NUMERIC(15, 2)
    ) AS PERC_NF_COM_PEDIDO
FROM NFSAIDA n
LEFT JOIN PEDIDO p
  ON p.ID = n.NUMEROORIGEM
GROUP BY n.EMPRESA
ORDER BY n.EMPRESA;

-- 3. Exemplos de NF com pedido encontrado
SELECT FIRST 20
    n.ID AS ID_NFSAIDA,
    n.EMPRESA,
    n.NOTAFISCAL,
    n.NUMEROORIGEM,
    p.ID AS ID_PEDIDO,
    p.NUMPEDIDO,
    n.CLIENTE,
    p.CLIENTE AS PEDIDO_CLIENTE,
    n.DATAEMISSAO,
    p.DATAEMISSAO AS DATA_PEDIDO
FROM NFSAIDA n
JOIN PEDIDO p
  ON p.ID = n.NUMEROORIGEM
ORDER BY n.ID;

-- 4. Exemplos de NF com NUMEROORIGEM preenchido mas sem pedido correspondente
SELECT FIRST 20
    n.ID AS ID_NFSAIDA,
    n.EMPRESA,
    n.NOTAFISCAL,
    n.NUMEROORIGEM,
    n.CLIENTE,
    n.DATAEMISSAO,
    n.NUMERO
FROM NFSAIDA n
LEFT JOIN PEDIDO p
  ON p.ID = n.NUMEROORIGEM
WHERE n.NUMEROORIGEM IS NOT NULL
  AND p.ID IS NULL
ORDER BY n.ID;

-- 5. Conferencia adicional:
--    checa se cliente da nota bate com cliente do pedido
SELECT
    COUNT(*) AS TOTAL_MATCHES,
    SUM(CASE WHEN n.CLIENTE = p.CLIENTE THEN 1 ELSE 0 END) AS MATCH_CLIENTE,
    SUM(CASE WHEN n.CLIENTE <> p.CLIENTE THEN 1 ELSE 0 END) AS DIVERGENCIA_CLIENTE,
    CAST(
        100.0 * SUM(CASE WHEN n.CLIENTE = p.CLIENTE THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0)
        AS NUMERIC(15, 2)
    ) AS PERC_MATCH_CLIENTE
FROM NFSAIDA n
JOIN PEDIDO p
  ON p.ID = n.NUMEROORIGEM;
