-- Validacao do relacionamento entre NFSAIDA e CLIENTE
-- Hipotese validada:
--   NFSAIDA.CLIENTE -> CLIENTE.CODIGO

-- 1. Resumo geral de cobertura
SELECT
    COUNT(*) AS TOTAL_NFSAIDA,
    SUM(CASE WHEN n.CLIENTE IS NOT NULL THEN 1 ELSE 0 END) AS NF_COM_CLIENTE,
    SUM(CASE WHEN c.CODIGO IS NOT NULL THEN 1 ELSE 0 END) AS NF_COM_CLIENTE_ENCONTRADO,
    SUM(CASE WHEN n.CLIENTE IS NOT NULL AND c.CODIGO IS NULL THEN 1 ELSE 0 END) AS NF_SEM_MATCH_CLIENTE,
    CAST(
        100.0 * SUM(CASE WHEN c.CODIGO IS NOT NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0)
        AS NUMERIC(15, 2)
    ) AS PERC_NF_COM_CLIENTE,
    CAST(
        100.0 * SUM(CASE WHEN n.CLIENTE IS NOT NULL AND c.CODIGO IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0)
        AS NUMERIC(15, 2)
    ) AS PERC_NF_SEM_MATCH
FROM NFSAIDA n
LEFT JOIN CLIENTE c
  ON c.CODIGO = n.CLIENTE;

-- 2. Resumo por empresa
SELECT
    n.EMPRESA,
    COUNT(*) AS TOTAL_NFSAIDA,
    SUM(CASE WHEN n.CLIENTE IS NOT NULL THEN 1 ELSE 0 END) AS NF_COM_CLIENTE,
    SUM(CASE WHEN c.CODIGO IS NOT NULL THEN 1 ELSE 0 END) AS NF_COM_CLIENTE_ENCONTRADO,
    SUM(CASE WHEN n.CLIENTE IS NOT NULL AND c.CODIGO IS NULL THEN 1 ELSE 0 END) AS NF_SEM_MATCH_CLIENTE,
    CAST(
        100.0 * SUM(CASE WHEN c.CODIGO IS NOT NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0)
        AS NUMERIC(15, 2)
    ) AS PERC_NF_COM_CLIENTE
FROM NFSAIDA n
LEFT JOIN CLIENTE c
  ON c.CODIGO = n.CLIENTE
GROUP BY n.EMPRESA
ORDER BY n.EMPRESA;

-- 3. Exemplos com match
SELECT FIRST 20
    n.ID AS ID_NFSAIDA,
    n.EMPRESA,
    n.NOTAFISCAL,
    n.CLIENTE AS CODIGO_CLIENTE_NF,
    c.CODIGO AS CODIGO_CLIENTE_CAD,
    c.NOME,
    c.RAZAOSOCIAL,
    n.CLI_RAZAO_SOCIAL
FROM NFSAIDA n
JOIN CLIENTE c
  ON c.CODIGO = n.CLIENTE
ORDER BY n.ID;

-- 4. Exemplos sem match
SELECT FIRST 20
    n.ID AS ID_NFSAIDA,
    n.EMPRESA,
    n.NOTAFISCAL,
    n.CLIENTE AS CODIGO_CLIENTE_NF,
    n.CLI_RAZAO_SOCIAL,
    n.DATAEMISSAO
FROM NFSAIDA n
LEFT JOIN CLIENTE c
  ON c.CODIGO = n.CLIENTE
WHERE n.CLIENTE IS NOT NULL
  AND c.CODIGO IS NULL
ORDER BY n.ID;

-- 5. Conferencia adicional:
--    compara o nome do cliente da nota com o cadastro, quando ambos existirem
SELECT FIRST 20
    n.ID AS ID_NFSAIDA,
    n.CLIENTE AS CODIGO_CLIENTE_NF,
    n.CLI_RAZAO_SOCIAL AS NOME_NA_NOTA,
    c.RAZAOSOCIAL AS NOME_NO_CADASTRO
FROM NFSAIDA n
JOIN CLIENTE c
  ON c.CODIGO = n.CLIENTE
WHERE COALESCE(TRIM(n.CLI_RAZAO_SOCIAL), '') <> ''
  AND COALESCE(TRIM(c.RAZAOSOCIAL), '') <> ''
  AND TRIM(n.CLI_RAZAO_SOCIAL) <> TRIM(c.RAZAOSOCIAL)
ORDER BY n.ID;
