-- Validacao de qualidade da primeira versao da fVendas
-- Base da fato:
--   NFSAIDA + NFSAIITE + CLIENTE + PRODUTO + PEDIDO

-- 1. Resumo geral da qualidade
SELECT
    COUNT(*) AS TOTAL_LINHAS_FATO_POTENCIAL,
    SUM(CASE WHEN COALESCE(n.CANCELADA, 'N') <> 'S' THEN 1 ELSE 0 END) AS LINHAS_ATIVAS,
    SUM(CASE WHEN COALESCE(n.CANCELADA, 'N') = 'S' THEN 1 ELSE 0 END) AS LINHAS_CANCELADAS,
    SUM(CASE WHEN ped.ID IS NOT NULL THEN 1 ELSE 0 END) AS LINHAS_COM_PEDIDO,
    SUM(CASE WHEN c.CODIGO IS NOT NULL THEN 1 ELSE 0 END) AS LINHAS_COM_CLIENTE,
    SUM(CASE WHEN p.ID IS NOT NULL THEN 1 ELSE 0 END) AS LINHAS_COM_PRODUTO,
    SUM(CASE WHEN COALESCE(i.CUSTOMEDIO, i.CUSTOOPERACIONAL) IS NOT NULL THEN 1 ELSE 0 END) AS LINHAS_COM_CUSTO,
    SUM(CASE WHEN n.IDVENDEDOR IS NOT NULL THEN 1 ELSE 0 END) AS LINHAS_COM_VENDEDOR,
    SUM(CASE WHEN COALESCE(n.DATASAIDA, n.DATAEMISSAO) IS NOT NULL THEN 1 ELSE 0 END) AS LINHAS_COM_DATA_VENDA,
    SUM(
        CASE
            WHEN COALESCE(
                NULLIF(TRIM(n.NOTAFISCAL), ''),
                NULLIF(TRIM(n.NUMERO), ''),
                CAST(n.ID AS VARCHAR(20))
            ) IS NOT NULL THEN 1
            ELSE 0
        END
    ) AS LINHAS_COM_CODIGO_VENDA,
    CAST(100.0 * SUM(CASE WHEN ped.ID IS NOT NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0) AS NUMERIC(15, 2)) AS PERC_COM_PEDIDO,
    CAST(100.0 * SUM(CASE WHEN c.CODIGO IS NOT NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0) AS NUMERIC(15, 2)) AS PERC_COM_CLIENTE,
    CAST(100.0 * SUM(CASE WHEN p.ID IS NOT NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0) AS NUMERIC(15, 2)) AS PERC_COM_PRODUTO,
    CAST(100.0 * SUM(CASE WHEN COALESCE(i.CUSTOMEDIO, i.CUSTOOPERACIONAL) IS NOT NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0) AS NUMERIC(15, 2)) AS PERC_COM_CUSTO,
    CAST(100.0 * SUM(CASE WHEN n.IDVENDEDOR IS NOT NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0) AS NUMERIC(15, 2)) AS PERC_COM_VENDEDOR
FROM NFSAIDA n
JOIN NFSAIITE i
  ON i.IDNFSAIDA = n.ID
LEFT JOIN CLIENTE c
  ON c.CODIGO = n.CLIENTE
LEFT JOIN PEDIDO ped
  ON ped.ID = n.NUMEROORIGEM
LEFT JOIN PRODUTO p
  ON p.ID = i.IDPRODUTO;

-- 2. Resumo por empresa
SELECT
    n.EMPRESA,
    COUNT(*) AS TOTAL_LINHAS,
    SUM(CASE WHEN ped.ID IS NOT NULL THEN 1 ELSE 0 END) AS LINHAS_COM_PEDIDO,
    SUM(CASE WHEN c.CODIGO IS NOT NULL THEN 1 ELSE 0 END) AS LINHAS_COM_CLIENTE,
    SUM(CASE WHEN p.ID IS NOT NULL THEN 1 ELSE 0 END) AS LINHAS_COM_PRODUTO,
    SUM(CASE WHEN COALESCE(i.CUSTOMEDIO, i.CUSTOOPERACIONAL) IS NOT NULL THEN 1 ELSE 0 END) AS LINHAS_COM_CUSTO,
    CAST(100.0 * SUM(CASE WHEN ped.ID IS NOT NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0) AS NUMERIC(15, 2)) AS PERC_COM_PEDIDO,
    CAST(100.0 * SUM(CASE WHEN c.CODIGO IS NOT NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0) AS NUMERIC(15, 2)) AS PERC_COM_CLIENTE,
    CAST(100.0 * SUM(CASE WHEN p.ID IS NOT NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0) AS NUMERIC(15, 2)) AS PERC_COM_PRODUTO
FROM NFSAIDA n
JOIN NFSAIITE i
  ON i.IDNFSAIDA = n.ID
LEFT JOIN CLIENTE c
  ON c.CODIGO = n.CLIENTE
LEFT JOIN PEDIDO ped
  ON ped.ID = n.NUMEROORIGEM
LEFT JOIN PRODUTO p
  ON p.ID = i.IDPRODUTO
GROUP BY n.EMPRESA
ORDER BY n.EMPRESA;

-- 3. Linhas que ficariam fora da fVendas por ausencia de cliente ou produto
SELECT FIRST 50
    n.ID AS ID_NFSAIDA,
    i.ID AS ID_NFSAIITE,
    n.EMPRESA,
    n.NOTAFISCAL,
    n.CLIENTE AS CODIGO_CLIENTE_NF,
    i.IDPRODUTO,
    n.NUMEROORIGEM,
    ped.NUMPEDIDO,
    c.CODIGO AS CLIENTE_ENCONTRADO,
    p.CODIGO AS PRODUTO_ENCONTRADO
FROM NFSAIDA n
JOIN NFSAIITE i
  ON i.IDNFSAIDA = n.ID
LEFT JOIN CLIENTE c
  ON c.CODIGO = n.CLIENTE
LEFT JOIN PEDIDO ped
  ON ped.ID = n.NUMEROORIGEM
LEFT JOIN PRODUTO p
  ON p.ID = i.IDPRODUTO
WHERE c.CODIGO IS NULL
   OR p.ID IS NULL
ORDER BY n.ID, i.ID;

-- 4. Linhas sem pedido vinculado
SELECT FIRST 50
    n.ID AS ID_NFSAIDA,
    i.ID AS ID_NFSAIITE,
    n.EMPRESA,
    n.NOTAFISCAL,
    n.NUMEROORIGEM,
    n.CLIENTE,
    i.IDPRODUTO
FROM NFSAIDA n
JOIN NFSAIITE i
  ON i.IDNFSAIDA = n.ID
LEFT JOIN PEDIDO ped
  ON ped.ID = n.NUMEROORIGEM
WHERE ped.ID IS NULL
ORDER BY n.ID, i.ID;

-- 5. Linhas sem custo
SELECT FIRST 50
    n.ID AS ID_NFSAIDA,
    i.ID AS ID_NFSAIITE,
    n.EMPRESA,
    n.NOTAFISCAL,
    i.IDPRODUTO,
    i.PRODNOME,
    i.CUSTOMEDIO,
    i.CUSTOOPERACIONAL
FROM NFSAIDA n
JOIN NFSAIITE i
  ON i.IDNFSAIDA = n.ID
WHERE COALESCE(i.CUSTOMEDIO, i.CUSTOOPERACIONAL) IS NULL
ORDER BY n.ID, i.ID;
