-- Validacao do relacionamento entre NFSAIITE e PRODUTO
-- Hipotese validada:
--   NFSAIITE.IDPRODUTO -> PRODUTO.ID

-- 1. Resumo geral de cobertura
SELECT
    COUNT(*) AS TOTAL_ITENS_NF,
    SUM(CASE WHEN i.IDPRODUTO IS NOT NULL THEN 1 ELSE 0 END) AS ITENS_COM_IDPRODUTO,
    SUM(CASE WHEN p.ID IS NOT NULL THEN 1 ELSE 0 END) AS ITENS_COM_PRODUTO_ENCONTRADO,
    SUM(CASE WHEN i.IDPRODUTO IS NOT NULL AND p.ID IS NULL THEN 1 ELSE 0 END) AS ITENS_SEM_MATCH_PRODUTO,
    CAST(
        100.0 * SUM(CASE WHEN p.ID IS NOT NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0)
        AS NUMERIC(15, 2)
    ) AS PERC_ITENS_COM_PRODUTO,
    CAST(
        100.0 * SUM(CASE WHEN i.IDPRODUTO IS NOT NULL AND p.ID IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0)
        AS NUMERIC(15, 2)
    ) AS PERC_ITENS_SEM_MATCH
FROM NFSAIITE i
LEFT JOIN PRODUTO p
  ON p.ID = i.IDPRODUTO;

-- 2. Resumo por empresa
SELECT
    n.EMPRESA,
    COUNT(*) AS TOTAL_ITENS_NF,
    SUM(CASE WHEN i.IDPRODUTO IS NOT NULL THEN 1 ELSE 0 END) AS ITENS_COM_IDPRODUTO,
    SUM(CASE WHEN p.ID IS NOT NULL THEN 1 ELSE 0 END) AS ITENS_COM_PRODUTO_ENCONTRADO,
    SUM(CASE WHEN i.IDPRODUTO IS NOT NULL AND p.ID IS NULL THEN 1 ELSE 0 END) AS ITENS_SEM_MATCH_PRODUTO,
    CAST(
        100.0 * SUM(CASE WHEN p.ID IS NOT NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0)
        AS NUMERIC(15, 2)
    ) AS PERC_ITENS_COM_PRODUTO
FROM NFSAIITE i
JOIN NFSAIDA n
  ON n.ID = i.IDNFSAIDA
LEFT JOIN PRODUTO p
  ON p.ID = i.IDPRODUTO
GROUP BY n.EMPRESA
ORDER BY n.EMPRESA;

-- 3. Exemplos com match
SELECT FIRST 20
    i.ID AS ID_NFSAIITE,
    i.IDNFSAIDA,
    i.ITEM,
    i.IDPRODUTO,
    p.CODIGO AS CODIGO_PRODUTO,
    p.NOME AS NOME_PRODUTO,
    i.PRODNOME AS NOME_PRODUTO_NA_NOTA,
    i.QUANTIDADE,
    i.VALORUNITARIO,
    i.VALORITEMLIQUIDO
FROM NFSAIITE i
JOIN PRODUTO p
  ON p.ID = i.IDPRODUTO
ORDER BY i.ID;

-- 4. Exemplos sem match
SELECT FIRST 20
    i.ID AS ID_NFSAIITE,
    i.IDNFSAIDA,
    i.ITEM,
    i.IDPRODUTO,
    i.PRODNOME AS NOME_PRODUTO_NA_NOTA,
    i.QUANTIDADE,
    i.VALORUNITARIO,
    i.VALORITEMLIQUIDO
FROM NFSAIITE i
LEFT JOIN PRODUTO p
  ON p.ID = i.IDPRODUTO
WHERE i.IDPRODUTO IS NOT NULL
  AND p.ID IS NULL
ORDER BY i.ID;

-- 5. Conferencia adicional:
--    mede se a descricao do item da nota se aproxima da descricao do cadastro
SELECT FIRST 20
    i.ID AS ID_NFSAIITE,
    i.IDPRODUTO,
    i.PRODNOME AS NOME_NOTA,
    p.NOME AS NOME_CADASTRO
FROM NFSAIITE i
JOIN PRODUTO p
  ON p.ID = i.IDPRODUTO
WHERE COALESCE(TRIM(i.PRODNOME), '') <> COALESCE(TRIM(p.NOME), '')
ORDER BY i.ID;
