-- Exploracao da tabela NFSAIITE
-- Assunto: itens de venda (item da nota fiscal de saida)
-- Contagem observada no inventario: 237386
-- PK candidata: ID
-- Chaves naturais candidatas: IDNFSAIDA + ITEM
-- FKs candidatas pelo nome: IDNFSAIDA, IDPRODUTO, IDPRODUTOLOTE, IDPRODUTOLOCAL, IDPRODUTOGRADE, IDTIPMVSAI, IDUNIDADE
-- Datas candidatas: ULTIMAALTERACAODB, FABPROPRIO, VENCPROPRIO

SELECT FIRST 20 *
FROM NFSAIITE;

SELECT
    TRIM(rf.RDB$FIELD_NAME) AS COLUNA,
    CASE f.RDB$FIELD_TYPE
        WHEN 7 THEN 'SMALLINT'
        WHEN 8 THEN 'INTEGER'
        WHEN 10 THEN 'FLOAT'
        WHEN 12 THEN 'DATE'
        WHEN 13 THEN 'TIME'
        WHEN 14 THEN 'CHAR'
        WHEN 16 THEN
            CASE
                WHEN f.RDB$FIELD_SUB_TYPE = 1 THEN 'NUMERIC'
                WHEN f.RDB$FIELD_SUB_TYPE = 2 THEN 'DECIMAL'
                ELSE 'BIGINT'
            END
        WHEN 27 THEN 'DOUBLE'
        WHEN 35 THEN 'TIMESTAMP'
        WHEN 37 THEN 'VARCHAR'
        WHEN 261 THEN 'BLOB'
        ELSE 'TIPO_' || f.RDB$FIELD_TYPE
    END AS TIPO_DADO,
    COALESCE(f.RDB$CHARACTER_LENGTH, f.RDB$FIELD_LENGTH) AS TAMANHO,
    CASE rf.RDB$NULL_FLAG
        WHEN 1 THEN 'NAO'
        ELSE 'SIM'
    END AS ACEITA_NULO
FROM RDB$RELATION_FIELDS rf
JOIN RDB$FIELDS f
  ON f.RDB$FIELD_NAME = rf.RDB$FIELD_SOURCE
WHERE TRIM(rf.RDB$RELATION_NAME) = 'NFSAIITE'
ORDER BY rf.RDB$FIELD_POSITION;

SELECT COUNT(*) AS TOTAL_LINHAS
FROM NFSAIITE;

SELECT 'ULTIMAALTERACAODB' AS COLUNA_DATA, MIN(ULTIMAALTERACAODB) AS MENOR_DATA, MAX(ULTIMAALTERACAODB) AS MAIOR_DATA FROM NFSAIITE
UNION ALL
SELECT 'FABPROPRIO', MIN(FABPROPRIO), MAX(FABPROPRIO) FROM NFSAIITE
UNION ALL
SELECT 'VENCPROPRIO', MIN(VENCPROPRIO), MAX(VENCPROPRIO) FROM NFSAIITE;

SELECT
    TRIM(rf.RDB$FIELD_NAME) AS COLUNA,
    CASE
        WHEN TRIM(rf.RDB$FIELD_NAME) = 'ID' THEN 'PK candidata'
        WHEN TRIM(rf.RDB$FIELD_NAME) IN ('IDNFSAIDA', 'ITEM') THEN 'Chave natural candidata'
        WHEN TRIM(rf.RDB$FIELD_NAME) STARTING WITH 'ID' THEN 'FK candidata'
        ELSE 'Analisar'
    END AS PAPEL_PROVAVEL
FROM RDB$RELATION_FIELDS rf
WHERE TRIM(rf.RDB$RELATION_NAME) = 'NFSAIITE'
  AND (
      TRIM(rf.RDB$FIELD_NAME) = 'ID'
      OR TRIM(rf.RDB$FIELD_NAME) IN ('IDNFSAIDA', 'ITEM')
      OR TRIM(rf.RDB$FIELD_NAME) STARTING WITH 'ID'
  )
ORDER BY rf.RDB$FIELD_POSITION;
