-- Exploracao da tabela PEDITE
-- Assunto: itens de venda (item do pedido)
-- Contagem observada no inventario: 103653
-- PK candidata: ID
-- Chaves naturais candidatas: IDPEDIDO + ITEM
-- FKs candidatas pelo nome: IDPEDIDO, IDPRODUTO, IDPRODUTOLOTE, IDPRODUTOLOCAL, IDPRODUTOGRADE, IDTIPMVSAI, IDUNIDADE
-- Datas candidatas: DATAEMISSAOORDEMCOMPRA, DATAPREVISTARECEBIMENTO, ULTIMAALTERACAODB, DATAENTREGA, DATA_CARGA, DATADEVOLUCAO, DATASTATUSADICIONAL, FABPROPRIO, VENCPROPRIO, DATAINSERCAO

SELECT FIRST 20 *
FROM PEDITE;

SELECT
    TRIM(rf.RDB$FIELD_NAME) AS COLUNA,
    CASE f.RDB$FIELD_TYPE
        WHEN 7 THEN 'SMALLINT'
        WHEN 8 THEN 'INTEGER'
        WHEN 10 THEN 'FLOAT'
        WHEN 12 THEN 'DATE'
        WHEN 13 THEN 'TIME'
        WHEN 14 THEN 'CHAR'
        WHEN 16 THEN
            CASE
                WHEN f.RDB$FIELD_SUB_TYPE = 1 THEN 'NUMERIC'
                WHEN f.RDB$FIELD_SUB_TYPE = 2 THEN 'DECIMAL'
                ELSE 'BIGINT'
            END
        WHEN 27 THEN 'DOUBLE'
        WHEN 35 THEN 'TIMESTAMP'
        WHEN 37 THEN 'VARCHAR'
        WHEN 261 THEN 'BLOB'
        ELSE 'TIPO_' || f.RDB$FIELD_TYPE
    END AS TIPO_DADO,
    COALESCE(f.RDB$CHARACTER_LENGTH, f.RDB$FIELD_LENGTH) AS TAMANHO,
    CASE rf.RDB$NULL_FLAG
        WHEN 1 THEN 'NAO'
        ELSE 'SIM'
    END AS ACEITA_NULO
FROM RDB$RELATION_FIELDS rf
JOIN RDB$FIELDS f
  ON f.RDB$FIELD_NAME = rf.RDB$FIELD_SOURCE
WHERE TRIM(rf.RDB$RELATION_NAME) = 'PEDITE'
ORDER BY rf.RDB$FIELD_POSITION;

SELECT COUNT(*) AS TOTAL_LINHAS
FROM PEDITE;

SELECT 'DATAEMISSAOORDEMCOMPRA' AS COLUNA_DATA, MIN(DATAEMISSAOORDEMCOMPRA) AS MENOR_DATA, MAX(DATAEMISSAOORDEMCOMPRA) AS MAIOR_DATA FROM PEDITE
UNION ALL
SELECT 'DATAPREVISTARECEBIMENTO', MIN(DATAPREVISTARECEBIMENTO), MAX(DATAPREVISTARECEBIMENTO) FROM PEDITE
UNION ALL
SELECT 'ULTIMAALTERACAODB', MIN(ULTIMAALTERACAODB), MAX(ULTIMAALTERACAODB) FROM PEDITE
UNION ALL
SELECT 'DATAENTREGA', MIN(DATAENTREGA), MAX(DATAENTREGA) FROM PEDITE
UNION ALL
SELECT 'DATA_CARGA', MIN(DATA_CARGA), MAX(DATA_CARGA) FROM PEDITE
UNION ALL
SELECT 'DATADEVOLUCAO', MIN(DATADEVOLUCAO), MAX(DATADEVOLUCAO) FROM PEDITE
UNION ALL
SELECT 'DATASTATUSADICIONAL', MIN(DATASTATUSADICIONAL), MAX(DATASTATUSADICIONAL) FROM PEDITE
UNION ALL
SELECT 'FABPROPRIO', MIN(FABPROPRIO), MAX(FABPROPRIO) FROM PEDITE
UNION ALL
SELECT 'VENCPROPRIO', MIN(VENCPROPRIO), MAX(VENCPROPRIO) FROM PEDITE
UNION ALL
SELECT 'DATAINSERCAO', MIN(DATAINSERCAO), MAX(DATAINSERCAO) FROM PEDITE;

SELECT
    TRIM(rf.RDB$FIELD_NAME) AS COLUNA,
    CASE
        WHEN TRIM(rf.RDB$FIELD_NAME) = 'ID' THEN 'PK candidata'
        WHEN TRIM(rf.RDB$FIELD_NAME) IN ('IDPEDIDO', 'ITEM') THEN 'Chave natural candidata'
        WHEN TRIM(rf.RDB$FIELD_NAME) STARTING WITH 'ID' THEN 'FK candidata'
        ELSE 'Analisar'
    END AS PAPEL_PROVAVEL
FROM RDB$RELATION_FIELDS rf
WHERE TRIM(rf.RDB$RELATION_NAME) = 'PEDITE'
  AND (
      TRIM(rf.RDB$FIELD_NAME) = 'ID'
      OR TRIM(rf.RDB$FIELD_NAME) IN ('IDPEDIDO', 'ITEM')
      OR TRIM(rf.RDB$FIELD_NAME) STARTING WITH 'ID'
  )
ORDER BY rf.RDB$FIELD_POSITION;
