-- Exploracao da tabela CAIXAVENDAITENS
-- Assunto: itens de venda (item de PDV / balcao)
-- Contagem observada no inventario: 16688
-- PK candidata: ID
-- Chaves naturais candidatas: IDCAIXAMOVIMENTO + SEQITEM
-- FKs candidatas pelo nome: IDCAIXAMOVIMENTO, IDPRODUTO, IDPRODUTOLOTE, IDPRODUTOLOCAL, IDPRODUTOGRADE, IDTIPMVSAI, IDUNIDADE, CLIENTE, IDVENDEDOR
-- Datas candidatas: DATAHORAMOV

SELECT FIRST 20 *
FROM CAIXAVENDAITENS;

SELECT
    TRIM(rf.RDB$FIELD_NAME) AS COLUNA,
    CASE f.RDB$FIELD_TYPE
        WHEN 7 THEN 'SMALLINT'
        WHEN 8 THEN 'INTEGER'
        WHEN 10 THEN 'FLOAT'
        WHEN 12 THEN 'DATE'
        WHEN 13 THEN 'TIME'
        WHEN 14 THEN 'CHAR'
        WHEN 16 THEN
            CASE
                WHEN f.RDB$FIELD_SUB_TYPE = 1 THEN 'NUMERIC'
                WHEN f.RDB$FIELD_SUB_TYPE = 2 THEN 'DECIMAL'
                ELSE 'BIGINT'
            END
        WHEN 27 THEN 'DOUBLE'
        WHEN 35 THEN 'TIMESTAMP'
        WHEN 37 THEN 'VARCHAR'
        WHEN 261 THEN 'BLOB'
        ELSE 'TIPO_' || f.RDB$FIELD_TYPE
    END AS TIPO_DADO,
    COALESCE(f.RDB$CHARACTER_LENGTH, f.RDB$FIELD_LENGTH) AS TAMANHO,
    CASE rf.RDB$NULL_FLAG
        WHEN 1 THEN 'NAO'
        ELSE 'SIM'
    END AS ACEITA_NULO
FROM RDB$RELATION_FIELDS rf
JOIN RDB$FIELDS f
  ON f.RDB$FIELD_NAME = rf.RDB$FIELD_SOURCE
WHERE TRIM(rf.RDB$RELATION_NAME) = 'CAIXAVENDAITENS'
ORDER BY rf.RDB$FIELD_POSITION;

SELECT COUNT(*) AS TOTAL_LINHAS
FROM CAIXAVENDAITENS;

SELECT 'DATAHORAMOV' AS COLUNA_DATA, MIN(DATAHORAMOV) AS MENOR_DATA, MAX(DATAHORAMOV) AS MAIOR_DATA
FROM CAIXAVENDAITENS;

SELECT
    TRIM(rf.RDB$FIELD_NAME) AS COLUNA,
    CASE
        WHEN TRIM(rf.RDB$FIELD_NAME) = 'ID' THEN 'PK candidata'
        WHEN TRIM(rf.RDB$FIELD_NAME) IN ('IDCAIXAMOVIMENTO', 'SEQITEM') THEN 'Chave natural candidata'
        WHEN TRIM(rf.RDB$FIELD_NAME) = 'CLIENTE' THEN 'FK candidata por codigo de negocio'
        WHEN TRIM(rf.RDB$FIELD_NAME) STARTING WITH 'ID' THEN 'FK candidata'
        ELSE 'Analisar'
    END AS PAPEL_PROVAVEL
FROM RDB$RELATION_FIELDS rf
WHERE TRIM(rf.RDB$RELATION_NAME) = 'CAIXAVENDAITENS'
  AND (
      TRIM(rf.RDB$FIELD_NAME) = 'ID'
      OR TRIM(rf.RDB$FIELD_NAME) IN ('IDCAIXAMOVIMENTO', 'SEQITEM', 'CLIENTE')
      OR TRIM(rf.RDB$FIELD_NAME) STARTING WITH 'ID'
  )
ORDER BY rf.RDB$FIELD_POSITION;
