-- Exploracao da tabela CLIENTE
-- Assunto: clientes
-- Contagem observada no inventario: 1355
-- PK candidatas: ID, CODIGO
-- Chaves naturais candidatas: CODIGO, CGCCPF
-- FKs candidatas pelo nome: IDVENDEDOR, IDFORMAPAGAMENTO, BANCO, IDPROMOTOR, CONTARECDESP, IDNATUREZARECEITA
-- Datas candidatas: DATAEMISSAO, DATACADASTRO, DATAULTIMAATUAL, DATAULTIMAVENDA, DATASITCADASTRO, ULTIMAALTERACAODB

SELECT FIRST 20 *
FROM CLIENTE;

SELECT
    TRIM(rf.RDB$FIELD_NAME) AS COLUNA,
    CASE f.RDB$FIELD_TYPE
        WHEN 7 THEN 'SMALLINT'
        WHEN 8 THEN 'INTEGER'
        WHEN 10 THEN 'FLOAT'
        WHEN 12 THEN 'DATE'
        WHEN 13 THEN 'TIME'
        WHEN 14 THEN 'CHAR'
        WHEN 16 THEN
            CASE
                WHEN f.RDB$FIELD_SUB_TYPE = 1 THEN 'NUMERIC'
                WHEN f.RDB$FIELD_SUB_TYPE = 2 THEN 'DECIMAL'
                ELSE 'BIGINT'
            END
        WHEN 27 THEN 'DOUBLE'
        WHEN 35 THEN 'TIMESTAMP'
        WHEN 37 THEN 'VARCHAR'
        WHEN 261 THEN 'BLOB'
        ELSE 'TIPO_' || f.RDB$FIELD_TYPE
    END AS TIPO_DADO,
    COALESCE(f.RDB$CHARACTER_LENGTH, f.RDB$FIELD_LENGTH) AS TAMANHO,
    CASE rf.RDB$NULL_FLAG
        WHEN 1 THEN 'NAO'
        ELSE 'SIM'
    END AS ACEITA_NULO
FROM RDB$RELATION_FIELDS rf
JOIN RDB$FIELDS f
  ON f.RDB$FIELD_NAME = rf.RDB$FIELD_SOURCE
WHERE TRIM(rf.RDB$RELATION_NAME) = 'CLIENTE'
ORDER BY rf.RDB$FIELD_POSITION;

SELECT COUNT(*) AS TOTAL_LINHAS
FROM CLIENTE;

SELECT 'DATAEMISSAO' AS COLUNA_DATA, MIN(DATAEMISSAO) AS MENOR_DATA, MAX(DATAEMISSAO) AS MAIOR_DATA FROM CLIENTE
UNION ALL
SELECT 'DATACADASTRO', MIN(DATACADASTRO), MAX(DATACADASTRO) FROM CLIENTE
UNION ALL
SELECT 'DATAULTIMAATUAL', MIN(DATAULTIMAATUAL), MAX(DATAULTIMAATUAL) FROM CLIENTE
UNION ALL
SELECT 'DATAULTIMAVENDA', MIN(DATAULTIMAVENDA), MAX(DATAULTIMAVENDA) FROM CLIENTE
UNION ALL
SELECT 'DATASITCADASTRO', MIN(DATASITCADASTRO), MAX(DATASITCADASTRO) FROM CLIENTE
UNION ALL
SELECT 'ULTIMAALTERACAODB', MIN(ULTIMAALTERACAODB), MAX(ULTIMAALTERACAODB) FROM CLIENTE;

SELECT
    TRIM(rf.RDB$FIELD_NAME) AS COLUNA,
    CASE
        WHEN TRIM(rf.RDB$FIELD_NAME) = 'ID' THEN 'PK candidata'
        WHEN TRIM(rf.RDB$FIELD_NAME) IN ('CODIGO', 'CGCCPF') THEN 'Chave natural candidata'
        WHEN TRIM(rf.RDB$FIELD_NAME) = 'BANCO' THEN 'FK candidata por codigo de negocio'
        WHEN TRIM(rf.RDB$FIELD_NAME) STARTING WITH 'ID' THEN 'FK candidata'
        ELSE 'Analisar'
    END AS PAPEL_PROVAVEL
FROM RDB$RELATION_FIELDS rf
WHERE TRIM(rf.RDB$RELATION_NAME) = 'CLIENTE'
  AND (
      TRIM(rf.RDB$FIELD_NAME) IN ('ID', 'CODIGO', 'CGCCPF', 'BANCO')
      OR TRIM(rf.RDB$FIELD_NAME) STARTING WITH 'ID'
  )
ORDER BY rf.RDB$FIELD_POSITION;
