-- Exploracao da tabela PRODUTO
-- Assunto: produtos
-- Contagem observada no inventario: 5422
-- PK candidatas: ID, CODIGO
-- Chaves naturais candidatas: CODIGO, CODFABRICANTE, REFERENCIA
-- FKs candidatas pelo nome: IDUNIDADE, IDUNIDADEPADRAO, IDCONVERSAOUNID, IDPRODUTOGRADE, IDPRODUTOMODELO, IDAPLICACAO
-- Datas candidatas: DATAALTERPRECO, DATAULTVENDA, DATAULTCOMPRA, ULTIMAALTERACAODB, DATAULTDESC, DATACADASTRO

SELECT FIRST 20 *
FROM PRODUTO;

SELECT
    TRIM(rf.RDB$FIELD_NAME) AS COLUNA,
    CASE f.RDB$FIELD_TYPE
        WHEN 7 THEN 'SMALLINT'
        WHEN 8 THEN 'INTEGER'
        WHEN 10 THEN 'FLOAT'
        WHEN 12 THEN 'DATE'
        WHEN 13 THEN 'TIME'
        WHEN 14 THEN 'CHAR'
        WHEN 16 THEN
            CASE
                WHEN f.RDB$FIELD_SUB_TYPE = 1 THEN 'NUMERIC'
                WHEN f.RDB$FIELD_SUB_TYPE = 2 THEN 'DECIMAL'
                ELSE 'BIGINT'
            END
        WHEN 27 THEN 'DOUBLE'
        WHEN 35 THEN 'TIMESTAMP'
        WHEN 37 THEN 'VARCHAR'
        WHEN 261 THEN 'BLOB'
        ELSE 'TIPO_' || f.RDB$FIELD_TYPE
    END AS TIPO_DADO,
    COALESCE(f.RDB$CHARACTER_LENGTH, f.RDB$FIELD_LENGTH) AS TAMANHO,
    CASE rf.RDB$NULL_FLAG
        WHEN 1 THEN 'NAO'
        ELSE 'SIM'
    END AS ACEITA_NULO
FROM RDB$RELATION_FIELDS rf
JOIN RDB$FIELDS f
  ON f.RDB$FIELD_NAME = rf.RDB$FIELD_SOURCE
WHERE TRIM(rf.RDB$RELATION_NAME) = 'PRODUTO'
ORDER BY rf.RDB$FIELD_POSITION;

SELECT COUNT(*) AS TOTAL_LINHAS
FROM PRODUTO;

SELECT 'DATAALTERPRECO' AS COLUNA_DATA, MIN(DATAALTERPRECO) AS MENOR_DATA, MAX(DATAALTERPRECO) AS MAIOR_DATA FROM PRODUTO
UNION ALL
SELECT 'DATAULTVENDA', MIN(DATAULTVENDA), MAX(DATAULTVENDA) FROM PRODUTO
UNION ALL
SELECT 'DATAULTCOMPRA', MIN(DATAULTCOMPRA), MAX(DATAULTCOMPRA) FROM PRODUTO
UNION ALL
SELECT 'ULTIMAALTERACAODB', MIN(ULTIMAALTERACAODB), MAX(ULTIMAALTERACAODB) FROM PRODUTO
UNION ALL
SELECT 'DATAULTDESC', MIN(DATAULTDESC), MAX(DATAULTDESC) FROM PRODUTO
UNION ALL
SELECT 'DATACADASTRO', MIN(DATACADASTRO), MAX(DATACADASTRO) FROM PRODUTO;

SELECT
    TRIM(rf.RDB$FIELD_NAME) AS COLUNA,
    CASE
        WHEN TRIM(rf.RDB$FIELD_NAME) = 'ID' THEN 'PK candidata'
        WHEN TRIM(rf.RDB$FIELD_NAME) IN ('CODIGO', 'CODFABRICANTE', 'REFERENCIA') THEN 'Chave natural candidata'
        WHEN TRIM(rf.RDB$FIELD_NAME) STARTING WITH 'ID' THEN 'FK candidata'
        ELSE 'Analisar'
    END AS PAPEL_PROVAVEL
FROM RDB$RELATION_FIELDS rf
WHERE TRIM(rf.RDB$RELATION_NAME) = 'PRODUTO'
  AND (
      TRIM(rf.RDB$FIELD_NAME) IN ('ID', 'CODIGO', 'CODFABRICANTE', 'REFERENCIA')
      OR TRIM(rf.RDB$FIELD_NAME) STARTING WITH 'ID'
  )
ORDER BY rf.RDB$FIELD_POSITION;
